import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';

import type { RootState, AppThunk } from '../../store';
import { gql } from '@apollo/client';
import gqlClient from '@client/utils/graphql.utils';
import { UIStatus } from '@client/utils/enums';
import { ChatUser, createChat, Chat, ChatMessage } from '@shared/models/chat.model';

export interface ChatState {
  chats: Chat[];
  selectedChatId: string | null;
  chatUsers: ChatUser[];
  uiStatus: UIStatus;
}

const initialState: ChatState = {
  chats: [],
  selectedChatId: null,
  chatUsers: [],
  uiStatus: UIStatus.IDLE,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const addChatAsync = createAsyncThunk('chat/addChatAsync', async () => {
  const mutation = gql`
    mutation AddChat($chat: ChatInput!) {
      addChat(chat: $chat) {
        ...ChatFields
      }
    }
  `;
  return gqlClient().mutate({ mutation, variables: { chat: createChat() } });
});

export const deleteChatAsync = createAsyncThunk('chat/deleteChatAsync', async (payload: { chatId: string }) => {
  const mutation = gql`
    mutation DeleteChat($chatId: String!) {
      deleteChat(chatId: $chatId)
    }
  `;
  return gqlClient().mutate({ mutation, variables: { chatId: payload.chatId } });
});

export const changeChatNameAsync = createAsyncThunk('chat/changeChatNameAsync', async (payload: { chatId: string; newName: string }) => {
  const mutation = gql`
    mutation ChangeChatName($chatId: String!, $newName: String!) {
      changeChatName(chatId: $chatId, newName: $newName) {
        ...ChatFields
      }
    }
  `;
  return gqlClient().mutate({ mutation, variables: { chatId: payload.chatId, newName: payload.newName } });
});

export const addChatMessageAsync = createAsyncThunk('chat/addChatMessageAsync', async (payload: { chatId: string; content: string }) => {
  const mutation = gql`
    mutation AddChatMessage($chatId: String!, $content: String!) {
      addChatMessage(chatId: $chatId, content: $content) {
        chatId
        message {
          ...ChatMessageFields
        }
      }
    }
  `;
  return gqlClient().mutate({ mutation, variables: { chatId: payload.chatId, content: payload.content } });
});

export const loadChatsAsync = createAsyncThunk('chat/loadChatsAsync', async () => {
  const query = gql`
    query LoadChats {
      chats {
        ...ChatFields
      }
    }
  `;
  return gqlClient().query({ query });
});

export const chatSlice = createSlice({
  name: 'chat',
  initialState,
  reducers: {
    addParticipantToChat: (state, action: PayloadAction<{ chatId: string; participantId: string }>) => {
      const { chatId, participantId } = action.payload;
      const chat = state.chats.find(chat => chat.id === chatId);
      const participant = state.chatUsers.find(user => user.id === participantId);
      if (chat && participant) {
        chat.participants.push(participant);
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: builder => {
    builder
      .addCase(addChatAsync.fulfilled, (state, action) => {
        type ChangeChatNameResponse = Chat;
        const addedChat = action.payload.data.addChat as ChangeChatNameResponse;
        state.chats.push(addedChat);
        state.selectedChatId = addedChat.id;
      })
      .addCase(deleteChatAsync.fulfilled, (state, action) => {
        type ChangeChatNameResponse = string;
        const deletedChatId = action.payload.data.deleteChat as ChangeChatNameResponse;
        if (deletedChatId) {
          state.chats = state.chats.filter(chat => chat.id !== deletedChatId);
          state.selectedChatId = state.chats.length ? state.chats[0].id : null;
        }
      })
      .addCase(changeChatNameAsync.fulfilled, (state, action) => {
        type ChangeChatNameResponse = Chat;
        const changedChat = action.payload.data.changeChatName as ChangeChatNameResponse;
        const chat = state.chats.find(chat => chat.id === changedChat.id);
        if (chat) {
          chat.name = changedChat.name;
        }
      })
      .addCase(addChatMessageAsync.fulfilled, (state, action) => {
        type AddChatMessageResponse = { chatId: string; message: ChatMessage };
        const { chatId, message } = action.payload.data.addChatMessage as AddChatMessageResponse;
        const chat = state.chats.find(chat => chat.id === chatId);
        if (chat) {
          chat.messages.push(message);
        }
      })
      .addCase(loadChatsAsync.fulfilled, (state, action) => {
        const chats = action.payload.data.chats;
        if (chats.length > 0) {
          state.selectedChatId = chats[0].id;
          state.chats = chats;
        }
      })
      .addMatcher(
        action => action.type.endsWith('/pending'),
        state => {
          state.uiStatus = UIStatus.LOADING;
        },
      )
      .addMatcher(
        action => action.type.endsWith('/rejected'),
        state => {
          state.uiStatus = UIStatus.FAILED;
        },
      )
      .addMatcher(
        action => action.type.endsWith('/fulfilled'),
        state => {
          state.uiStatus = UIStatus.IDLE;
        },
      );
  },
});

export const { addParticipantToChat } = chatSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectChatState = (state: RootState) => state.chat;
export const selectChats = (state: RootState) => state.chat.chats;
export const selectSelectedChat = (state: RootState) => state.chat.chats.find(chat => chat.id === state.chat.selectedChatId) || null;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectChatState(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount));
//     }
//   };

export default chatSlice.reducer;
